### ISSUE TITLE
The subtraction in Containers.Integer_Stacks is wrong

### ISSUE THREAD

**Issue by oherrala** [Entomy/Containers#2]
I watched your video https://www.youtube.com/watch?v=m8wWEI_ZLMU about RPN calculator and spotted a mistake.

Subtraction in RPN works by popping two numbers from the stack and subtracting the top one from the bottom one. Expression `2 1 -` should equal `1`, but your code calculates `1 - 2` which produces `-1`.

The code

https://github.com/Entomy/Containers/blob/153b0af24384c71e2cd31e7ab785737db4ecc49e/Containers.Integer_Stacks.adb#L13-L16

does it wrong way around.

This mistake is also hidden by the fact that in tests 

https://github.com/Entomy/Containers/blob/153b0af24384c71e2cd31e7ab785737db4ecc49e/tests/stackinttests.adb#L23-L24

you do `6 - 6 = 0` which works both ways.

**Comment by Entomy** [comment]
Does this apply for division as well? `4 2 /` would be `2` or `0.5`?

**Comment by oherrala** [comment]
This applies to division also. The old an trustworthy Unix `dc(1)` says:

```console
$ echo '4 2 / p' | dc
2
```

**Comment by Entomy** [comment]
Should be fixed. Reopen if necessary.

**Comment by Entomy** [comment]
Oops! I never changed the docs!

I've thought about what you said, and I agree the older way is more intuitive. I'll change those.
